apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    targetRevision: 1.14.3
    chart: external-dns
    helm:
      values: |
        provider: aws
        aws:
          region: us-east-1
        # Set to public to update public Route53 zones, or private for internal
        domainFilters: []
        policy: sync
        txtOwnerId: "valkyrie-cluster"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
