apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-delete-chaos
  namespace: demo
spec:
  engineState: "active"
  appinfo:
    appns: "demo"
    applabel: "app=vote"
    appkind: "deployment"
  chaosServiceAccount: chaos-admin
  experiments:
    - name: generic-pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: "30"
            - name: CHAOS_INTERVAL
              value: "10"
            - name: FORCE
              value: "false"
