---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-admin
  namespace: demo
  labels:
    name: chaos-admin
    app.kubernetes.io/part-of: litmus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaos-admin
  namespace: demo
  labels:
    name: chaos-admin
    app.kubernetes.io/part-of: litmus
rules:
- apiGroups: ["", "apps", "batch", "litmuschaos.io"]
  resources: ["pods", "deployments", "jobs", "chaosengines", "chaosexperiments", "chaosresults", "events"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chaos-admin
  namespace: demo
  labels:
    name: chaos-admin
    app.kubernetes.io/part-of: litmus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chaos-admin
subjects:
- kind: ServiceAccount
  name: chaos-admin
  namespace: demo
